### ISSUE TITLE
weiteres Programm fürs Wiki

### ISSUE THREAD

**Issue by hmt** [opensource21/sze#7]
Hallo,

ich habe gerade Dein Programm entdeckt, sehr schön!
Von mir gibt es ebenfalls zwei, eins aktuell, eins nicht mehr in Benutzung:

neu und als App für alle gängigen Betriebssysteme: https://github.com/schild-report/schild.report
alt und serverbasiert: https://github.com/hmt/sahib

**Comment by opensource21** [comment]
Danke für die Rückmeldung. Ich habe Deine Reporting-Lösung in die Wiki-Seite integriert und auch das Wiki mal angepasst. Aktuell habe ich leider keine Zeit mehr gefunden, dass Programm zu betreuen, so dass es aktuell nicht mehr genutzt wird.
